# Generated by Django 4.1.5 on 2023-02-14 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='arr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='way',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 14, 14, 36, 47, 484755)),
        ),
    ]
