# Generated by Django 4.1.5 on 2023-02-14 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_way_arr_alter_way_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='way',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 14, 14, 42, 33, 881961)),
        ),
    ]
