# Generated by Django 4.1.5 on 2023-02-18 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_way_time_alter_way_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='way',
            name='s',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='way',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 10, 50, 10, 482522)),
        ),
    ]
