# Generated by Django 4.1.5 on 2023-02-18 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_alter_way_created_at_alter_way_s_alter_way_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='s',
        ),
        migrations.AddField(
            model_name='way',
            name='distance',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='way',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 11, 7, 30, 737382)),
        ),
        migrations.DeleteModel(
            name='Pavilion',
        ),
    ]
