# Generated by Django 4.1.5 on 2023-02-18 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_remove_way_s_way_distance_alter_way_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 11, 8, 46, 979412)),
        ),
    ]
