# Generated by Django 4.1.5 on 2023-02-18 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_alter_way_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 11, 10, 42, 188885)),
        ),
    ]
